{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.kr328.kaidl",
    "module": "kaidl",
    "version": "1.15",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kaidl-1.15.jar",
          "url": "kaidl-1.15.jar",
          "size": 59141,
          "sha512": "fef9722dee060b2c36f8f6ed8955ffb22ce9becd82ca37a4e84b804b87a619a273951a54f6d34aac753c6c1355f571771110acb6acfec9fd38bd4b166fd5ce4e",
          "sha256": "c502f8b2a78d6b089a735484fcf9015dde90142b10bb59b550964816cdadf76b",
          "sha1": "55009d227c7341e44c21cc14326b5c1c8579a037",
          "md5": "748d75c98fd18ce76959d870a3362a9c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.5.30"
          }
        },
        {
          "group": "com.google.devtools.ksp",
          "module": "symbol-processing-api",
          "version": {
            "requires": "1.5.30-1.0.0"
          }
        },
        {
          "group": "com.squareup",
          "module": "kotlinpoet",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "kaidl-1.15.jar",
          "url": "kaidl-1.15.jar",
          "size": 59141,
          "sha512": "fef9722dee060b2c36f8f6ed8955ffb22ce9becd82ca37a4e84b804b87a619a273951a54f6d34aac753c6c1355f571771110acb6acfec9fd38bd4b166fd5ce4e",
          "sha256": "c502f8b2a78d6b089a735484fcf9015dde90142b10bb59b550964816cdadf76b",
          "sha1": "55009d227c7341e44c21cc14326b5c1c8579a037",
          "md5": "748d75c98fd18ce76959d870a3362a9c"
        }
      ]
    }
  ]
}
